
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
            <main
      className="max-w-full min-h-screen  bg-bg-default text-fg-default"
      style={{
        backgroundImage: "url('/images/bg-main.svg')",
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'cover',
      }}
    > 
     
        {children}
        </main>
      </body>
    </html>
  );
}
